<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FormController extends Controller
{


    public function submitForm(Request $request)
    {
        // التحقق من صحة البيانات
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email',
            'phone' => 'required|string|max:15',
            'password' => 'required|string|min:6',
            'department' => 'required',
            'dentist' => 'required|string|max:255',
            'general_surgery' => 'required|string|max:255',
            'plastic_surgery' => 'required|string|max:255',
            'dermatology' => 'required|string|max:255',
            'neurology' => 'required|string|max:255',
            'pediatrics' => 'required|string|max:255',
            'opthalmology' => 'required|string|max:255',
            'urology' => 'required|string|max:255',
            'gynecology' => 'required|string|max:255',
            'orthopedics' => 'required|string|max:255',
            'cardiology' => 'required|string|max:255',
            'ent' => 'required|string|max:255',
            'oncology' => 'required|string|max:255',
            'anesthesia' => 'required|string|max:255',
            'psychiatry' => 'required|string|max:255',
            'neurosurgery' => 'required|string|max:255',
            'icu' => 'required|string|max:255',
            'emergency' => 'required|string|max:255',
            'geriatrics' => 'required|string|max:255',
            'radiology' => 'required|string|max:255',
            'pathology' => 'required|string|max:255',
            'nuclear_medicine' => 'required|string|max:255',
            'hematology' => 'required|string|max:255',
            'rheumatology' => 'required|string|max:255',
            'infectious_diseases' => 'required|string|max:255',
            'endocrinology' => 'required|string|max:255',
            'nephrology' => 'required|string|max:255',
            'pulmonology' => 'required|string|max:255',
             
             'allergy' => 'required|string|max:255',
    'gastroenterology' => 'required|string|max:255',
    'clinical_pharmacology' => 'required|string|max:255',
    'family_medicine' => 'required|string|max:255',
    'public_health' => 'required|string|max:255',
    'occ_health' => 'required|string|max:255',
    'health_management' => 'required|string|max:255',
    'forensic_medicine' => 'required|string|max:255',
    'sports_medicine' => 'required|string|max:255',
    'geriatric_medicine' => 'required|string|max:255',
    'audiology' => 'required|string|max:255',
    'neurobrain_surgery' => 'required|string|max:255',
    'spine_surgery' => 'required|string|max:255',
    'icsi_and_ivf' => 'required|string|max:255',
    'pediatric_surgery' => 'required|string|max:255',
    'cardiothoracic_surgery' => 'required|string|max:255',
    'allergy_and_immunology' => 'required|string|max:255',
    'orthopedics_surgery' => 'required|string|max:255',
    'pain_management_medicine' => 'required|string|max:255',
    'vascular_surgery' => 'required|string|max:255',
    'pets' => 'required|string|max:255',
    'oncology_surgery' => 'required|string|max:255',
    'vascular' => 'required|string|max:255',
    'addiction_problems_consultant' => 'required|string|max:255',
    'sexual_problems_consultant' => 'required|string|max:255',
    'tooth_implant' => 'required|string|max:255',
    'skin_beautification' => 'required|string|max:255',
    'reproductive_system' => 'required|string|max:255',
    'therapeutic_feeding' => 'required|string|max:255',
    'growth_monitoring' => 'required|string|max:255',
    'nerve_implantation' => 'required|string|max:255',
    'addiction' => 'required|string|max:255',
    'behavior_modification' => 'required|string|max:255',
    'family_guidance' => 'required|string|max:255',
    'rheumatism' => 'required|string|max:255',
    'athletic_medicine' => 'required|string|max:255',
    'joints' => 'required|string|max:255',
    'ivf' => 'required|string|max:255',
    'endoscopy' => 'required|string|max:255',
    'diabetes' => 'required|string|max:255',
    'kidney_diseases' => 'required|string|max:255',
    'blood_and_immunology' => 'required|string|max:255',
    'opthalmic_surgery_and_laser' => 'required|string|max:255',
    'liposuction' => 'required|string|max:255',
    'burn_treatment' => 'required|string|max:255',
    'internist' => 'required|string|max:255',
    'nutrition' => 'required|string|max:255',
    'liver_diseases' => 'required|string|max:255',
    'echo' => 'required|string|max:255',
    'pets_vaccinations' => 'required|string|max:255',
    'pets_grooming' => 'required|string|max:255',
    'difficulty_learning' => 'required|string|max:255',
    'orals_and_maxillofacial_surgery' => 'required|string|max:255',
    'clinic' => 'required|string|max:255',
    'home_visit' => 'required|string|max:255',
    'online_consultant' => 'required|string|max:255',
    'city' => 'required|string|max:255',
    'cairo' => 'required|string|max:255',
    'giza' => 'required|string|max:255',
    'alexandria' => 'required|string|max:255',
    'qena' => 'required|string|max:255',
    'kafr_el_sheikh' => 'required|string|max:255',
    'sinai' => 'required|string|max:255',
    'minya' => 'required|string|max:255',
    'port_said' => 'required|string|max:255',
    'suez' => 'required|string|max:255',
    'luxor' => 'required|string|max:255',
    'dakahlia' => 'required|string|max:255',
    'gharbia' => 'required|string|max:255',
    'assuit' => 'required|string|max:255',
    'qalyubia' => 'required|string|max:255',
    'ismailia' => 'required|string|max:255',
    'faiyum' => 'required|string|max:255',
    'sharqia' => 'required|string|max:255',
    'aswan' => 'required|string|max:255',
    'damietta' => 'required|string|max:255',
    'beheira' => 'required|string|max:255',
    'sohag' => 'required|string|max:255',
    'red_sea' => 'required|string|max:255',
    'monufia' => 'required|string|max:255',
    'matrouh' => 'required|string|max:255',
    'wadi_geded' => 'required|string|max:255',
    'riyadh' => 'required|string|max:255',
    'jeddah' => 'required|string|max:255',
    'mecca' => 'required|string|max:255',
    'north_coast_sahel' => 'required|string|max:255',
    'location' => 'required|string|max:255',
    'scientific_certificate_image' => 'required|file|mimes:jpg,png,jpeg|max:2048',
    'syndicate_image' => 'required|file|mimes:jpg,png,jpeg|max:2048',
    'clinic_photos' => 'required|file|mimes:jpg,png,jpeg|max:2048',
    'logo' => 'required|file|mimes:jpg,png,jpeg|max:2048',
    'doctor_image' => 'required|file|mimes:jpg,png,jpeg|max:2048',
    'professional_license' => 'required|file|mimes:jpg,png,jpeg|max:2048',
    'choose_file' => 'required|string|max:255',
    'no_file_chosen' => 'required|string|max:255',   
        ]);

        // معالجة البيانات (تخزينها في قاعدة البيانات أو تنفيذ إجراءات أخرى)

        // إعادة توجيه مع رسالة نجاح
        return redirect()->route('form.show')->with('success', __('messages.submitted_success'));
    }



}
